{% set version = "5.0" %}

package:
  name: zope.event
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/z/zope.event/zope.event-{{ version }}.tar.gz
  sha256: bac440d8d9891b4068e2b5a2c5e2c9765a9df762944bda6955f96bb9b91e67cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools

test:
  imports:
    - zope
    - zope.event
  commands:
    - pip check
    - pytest -vv --pyargs zope.event.tests --cov=zope.event --cov-report=term-missing:skip-covered
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/zopefoundation/zope.event
  summary: Very basic event publishing system
  license: ZPL-2.1
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  doc_url: https://zopeevent.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
