{% set version = "4.6" %}

package:
  name: zope.event
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/z/zope.event/zope.event-{{ version }}.tar.gz
  sha256: 81d98813046fc86cc4136e3698fee628a3282f9c320db18658c21749235fce80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - setuptools

test:
  imports:
    - zope
    - zope.event
  commands:
    - pip check
    - pytest -vv --pyargs zope.event.tests --cov=zope.event --cov-report=term-missing:skip-covered
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/zopefoundation/zope.event
  summary: Very basic event publishing system
  license: ZPL-2.1
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  doc_url: https://zopeevent.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
