{% set name = "zope.event" %}
{% set version = "4.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81d98813046fc86cc4136e3698fee628a3282f9c320db18658c21749235fce80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools

test:
  imports:
    - zope
    - zope.event
  commands:
    - python -m pip check
    - python -m pytest -vv --pyargs zope.event.tests --cov zope.event
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/zopefoundation/zope.event
  summary: Very basic event publishing system
  license: ZPL-2.1
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  doc_url: https://zopeevent.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
