{% set version = "5.1" %}

package:
  name: zope.event
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/z/zope.event/zope_event-{{ version }}.tar.gz
  sha256: a153660e0c228124655748e990396b9d8295d6e4f546fa1b34f3319e1c666e7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    # uses `pkg_resources`
    - setuptools

test:
  imports:
    - zope
    - zope.event
  commands:
    - pip check
    - pytest -vv --pyargs zope.event.tests --cov=zope.event --cov-report=term-missing:skip-covered
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://github.com/zopefoundation/zope.event
  summary: Very basic event publishing system
  license: ZPL-2.1
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  doc_url: https://zopeevent.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
